mtzcode2dtype = {
    "H" : "HKL",
    "J" : "Intensity",
    "F" : "SFAmplitude",
    "D" : "AnomalousDifference",
    "Q" : "Stddev",
    "G" : "FriedelSFAmplitude",
    "L" : "StddevFriedelSF",
    "K" : "FriedelIntensity",
    "M" : "StddevFriedelI",
    "E" : "NormalizedSFAmplitude",
    "P" : "Phase",
    "W" : "Weight",
    "A" : "HendricksonLattman",
    "B" : "Batch",
    "Y" : "M/ISYM",
    "I" : "MTZInt",
    "R" : "MTZReal"
}
